// @ts-check
import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import starlight from '@astrojs/starlight'
import { defineConfig } from 'astro/config'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const MANIFEST_PATH = path.join(__dirname, 'upstream', 'manifest.json')

function readManifest() {
  if (!existsSync(MANIFEST_PATH))
    return null
  try {
    return JSON.parse(readFileSync(MANIFEST_PATH, 'utf8'))
  }
  catch {
    return null
  }
}

const SECTION_ORDER = ['use-dify', 'self-host', 'develop-plugin', 'api-reference']

/** @type {Record<string, string>} */
const SECTION_LABELS = {
  'use-dify': 'Use Dify',
  'self-host': 'Self Host',
  'develop-plugin': 'Develop Plugin',
  'api-reference': 'API Reference',
}

/**
 * Build sidebar from manifest.
 * Each top-level directory becomes a collapsible group with autogenerated sub-items.
 * @param {any} manifest
 */
function buildSidebar(manifest) {
  if (!manifest || !Array.isArray(manifest.files)) {
    return SECTION_ORDER.map(section => ({
      label: SECTION_LABELS[section] ?? section,
      autogenerate: { directory: section },
    }))
  }

  const sections = new Set()
  for (const file of manifest.files) {
    const topDir = file.split('/')[0]
    if (topDir)
      sections.add(topDir)
  }

  /** @type {string[]} */
  const sorted = [...sections].sort((a, b) => {
    const ai = SECTION_ORDER.indexOf(a)
    const bi = SECTION_ORDER.indexOf(b)
    return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi)
  })

  return sorted.map((/** @type {string} */ section) => ({
    label: SECTION_LABELS[section] ?? section.charAt(0).toUpperCase() + section.slice(1).replace(/-/g, ' '),
    collapsed: true,
    autogenerate: { directory: section },
  }))
}

const manifest = readManifest()
const sidebar = buildSidebar(manifest)

export default defineConfig({
  site: process.env.SITE_URL || 'https://docs.dify.ai',
  integrations: [
    starlight({
      title: 'Dify Docs',
      description: 'Dify is an open-source platform for building AI applications.',
      defaultLocale: 'root',
      locales: {
        'root': {
          label: 'English',
          lang: 'en',
        },
        'zh-cn': {
          label: '简体中文',
          lang: 'zh-CN',
        },
        'ja': {
          label: '日本語',
          lang: 'ja',
        },
      },
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/langgenius/dify',
        },
      ],
      sidebar,
    }),
  ],
})
